# Generated by Django 4.1.1 on 2022-09-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_rename_person_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porfolio',
            new_name='Portfolio',
        ),
    ]
